package model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 25 14:37:39 CET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GehaltJobsNationImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GehaltJobsNationImpl () {}
}

