package model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 26 16:36:10 CET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GehaltBerufungImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GehaltBerufungImpl () {}
}

