package model.queries;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 25 13:46:48 CET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrtAbteilungRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Abteilung,
        Abteilungsleiter,
        Adresse,
        Stadt,
        Plz,
        Landeskreis,
        Land,
        Region;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index () {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex () {
            return firstIndex;
        }

        protected static int count () {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues () {
            if ( vals == null ) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ABTEILUNG = AttributesEnum.Abteilung.index();
    public static final int ABTEILUNGSLEITER = AttributesEnum.Abteilungsleiter.index();
    public static final int ADRESSE = AttributesEnum.Adresse.index();
    public static final int STADT = AttributesEnum.Stadt.index();
    public static final int PLZ = AttributesEnum.Plz.index();
    public static final int LANDESKREIS = AttributesEnum.Landeskreis.index();
    public static final int LAND = AttributesEnum.Land.index();
    public static final int REGION = AttributesEnum.Region.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OrtAbteilungRowImpl () {}
}

