package model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 25 13:46:48 CET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrtAbteilungImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OrtAbteilungImpl () {}
}

